#!/usr/bin/env python3
# Sets up a pwntools environment
import os
import sys

def main():
	if os.path.isfile('./solve.py'):
		print("solve.py already exists!")
		exit(-1)

	if len(sys.argv) != 2:
		print("Usage: setup {path of elf}")
		exit(-1)

	with open('./solve.py', 'w') as solve_f:
		solve_f.write(

f'''#!/usr/bin/env python3
from pwn import *
context.binary = exe = ELF('./{sys.argv[1]}')
context.kernel = context.arch
context.terminal = ["tmux", "splitw", "-h"]

rop = ROP(exe)

# shellcode to read a file:
# sh = shellcraft.open("/flag.txt")
# sh += shellcraft.read(3, "rsp", 0x1000)
# sh += shellcraft.write(1, "rsp", "rax")

io = gdb.debug('./{sys.argv[1]}')

io.interactive()
'''
		)

if __name__ == "__main__":
	main()
